### ISSUE TITLE
Introduction to ROS

### ISSUE THREAD

**Issue by akshatha-k** [RoboManipal-9-0/Coding-FirstYears#1]
## Install ROS
Refer to the [INSTALL_ROS](https://github.com/RoboManipal-9-0/Coding-FirstYears/blob/master/INSTALL_ROS.md) for installing ROS. 

## Familiarise with ROS Documentation
Refer to the [ROS Documentation](http://wiki.ros.org/) to get started with the basic concepts 
This week you're expected to complete the basic concepts required such as nodes, services, messages etc. Do not be intimidated by the terms ( You are also not required to memorise code syntax) . The learning curve for ROS is exponential and you will be working on visuals soon. 

## ROS Ignite Academy Courses 
Here's a [Youtube Channel](https://youtu.be/DLVyc9hOvk8) that has pretty good beginner tutorials such as ones to write publisher subscriber nodes. 

This is a course in basic ROS. [ROS Ignite academy](http://www.theconstructsim.com/construct-learn-develop-robots-using-ros/robotigniteacademy_learnros/ros-courses-library/ros-python-course/). Although, you will have to modify your codes as the course guides you through the online ROS environment. 

## Tasks for this week 
Make sure your codes are well commented.
- [ ] ROS publisher node to publish integer values.
(Echo the rostopic to the command line to test your code)
- [ ] ROS Subscriber node to read the values published by the above publisher node. 
- [ ] Learn about ROS messages 
- [ ] Read up how to write publisher and subscriber nodes on Arduino
[ROS Arduino](http://wiki.ros.org/rosserial_arduino/Tutorials/Hello%20World)
- [ ] Step 1: Write a publisher node on Arduino that reads values from the IR/ Ultrasonic sensor and publishes them over serial. Echo the ros topic
- [ ] Step 2: Create a subscriber on that subscribes to this message and blinks an LED based on a threshold. ( eg. If IR value greater than 25 it lights the LED)

### Note: 
- Link this issue to your commits each day. (Do not make commits without a following message) 
- Open another 'bug' issue and assign it to your teammates/ seniors if you face any error
- The last person to be done with the tasks, checks the list closes the issue once all of them are checked.
- When ROS core is running the Arduino serial monitor is unavailable. To upload your code, shutdown ros core and then upload.
