### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by Ojaswi2223** [RoboManipal-9-0/Coding-FirstYears#2]
## Tasks for Alignment

- [x] Testing Ultrasonic Sensors
- [x] Testing alignment without wheels against the wall.
- [ ] Testing alignment without wheels against the block.
- [x] Testing alignment with wheels against the wall.
- [ ] Testing alignment with wheels against the box.
